// automatically generated by the FlatBuffers compiler, do not modify

package GameServer

const (
	ProtocolTypeTestProtocol = 0
)

var EnumNamesProtocolType = map[int]string{
	ProtocolTypeTestProtocol:"TestProtocol",
}

