// automatically generated by the FlatBuffers compiler, do not modify

package TestProtocol

const (
	MessageTypeTestPing = 0
	MessageTypeTestPong = 1
)

var EnumNamesMessageType = map[int]string{
	MessageTypeTestPing:"TestPing",
	MessageTypeTestPong:"TestPong",
}

