// automatically generated by the FlatBuffers compiler, do not modify

package TestProtocol

const (
	ProtocolTypeTestPing = 0
	ProtocolTypeTestPong = 1
)

var EnumNamesProtocolType = map[int]string{
	ProtocolTypeTestPing:"TestPing",
	ProtocolTypeTestPong:"TestPong",
}

