// automatically generated by the FlatBuffers compiler, do not modify

package TestProtocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TestPong struct {
	_tab flatbuffers.Table
}

func GetRootAsTestPong(buf []byte, offset flatbuffers.UOffsetT) *TestPong {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TestPong{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TestPong) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TestPong) IntValue() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TestPong) MutateIntValue(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func TestPongStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TestPongAddIntValue(builder *flatbuffers.Builder, intValue int32) {
	builder.PrependInt32Slot(0, intValue, 0)
}
func TestPongEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
