// Code generated by protoc-gen-go.
// source: TestProtocol.proto
// DO NOT EDIT!

/*
Package TestProtocol is a generated protocol buffer package.

It is generated from these files:
	TestProtocol.proto

It has these top-level messages:
	Test
*/
package TestProtocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Test_EnumTest int32

const (
	Test_Test1 Test_EnumTest = 0
	Test_Test2 Test_EnumTest = 1
	Test_Test3 Test_EnumTest = 2
)

var Test_EnumTest_name = map[int32]string{
	0: "Test1",
	1: "Test2",
	2: "Test3",
}
var Test_EnumTest_value = map[string]int32{
	"Test1": 0,
	"Test2": 1,
	"Test3": 2,
}

func (x Test_EnumTest) String() string {
	return proto.EnumName(Test_EnumTest_name, int32(x))
}
func (Test_EnumTest) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Test struct {
	TestString string `protobuf:"bytes,1,opt,name=testString" json:"testString,omitempty"`
	TestInt    int32  `protobuf:"varint,2,opt,name=testInt" json:"testInt,omitempty"`
}

func (m *Test) Reset()                    { *m = Test{} }
func (m *Test) String() string            { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()               {}
func (*Test) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*Test)(nil), "Test")
	proto.RegisterEnum("Test_EnumTest", Test_EnumTest_name, Test_EnumTest_value)
}

func init() { proto.RegisterFile("TestProtocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x0a, 0x49, 0x2d, 0x2e,
	0x09, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x2b, 0x00, 0x31, 0x94, 0x72, 0xb9, 0x58,
	0x40, 0xa2, 0x42, 0x72, 0x5c, 0x5c, 0x25, 0x40, 0x3a, 0xb8, 0xa4, 0x28, 0x33, 0x2f, 0x5d, 0x82,
	0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0x49, 0x44, 0x48, 0x82, 0x8b, 0x1d, 0xc4, 0xf3, 0xcc, 0x2b,
	0x91, 0x60, 0x02, 0x4a, 0xb2, 0x06, 0xc1, 0xb8, 0x4a, 0xda, 0x5c, 0x1c, 0xae, 0x79, 0xa5, 0xb9,
	0x60, 0x53, 0x38, 0xb9, 0x58, 0x41, 0xb4, 0xa1, 0x00, 0x03, 0x8c, 0x69, 0x24, 0xc0, 0x08, 0x63,
	0x1a, 0x0b, 0x30, 0x25, 0xb1, 0x81, 0x6d, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x6d,
	0x9b, 0xf6, 0x8b, 0x00, 0x00, 0x00,
}
